### ISSUE TITLE
Move to MHS I/O?

### ISSUE THREAD

**Issue by AbhinavMadahar** [Charles-T-King/Charles-T-King.github.io#1]
MHS I/O is a new club that makes websites for the school, so it makes sense for MHS I/O to remake and maintain the CTK website. We would probably start development in October or November.

**Comment by conorgil** [comment]
I have definitely not given this project the appropriate attention that it
deserves. It makes tons of sense for the club to take over development and
maintenance of the website. Great idea.

I'd love to help facilitate the group taking ownership of the project. Can
we schedule some time to discuss some of the security concerns which the
application needs to consider during its development?

**Comment by AbhinavMadahar** [comment]
Yes, of course. Can we talk on Facebook messenger? I'm the only Abhinav Madahar on Facebook, so just send me a message and we can find a time.

**Comment by AbhinavMadahar** [comment]
As it turns out, I already set my senior name alias. Just send me an email at abhinavmadahar@gmail.com
